const coursesData = [
  {
    id: 1,
    title: "Become a product Manager learn the skills & job.",
    slug:"become-a-product-manager-learn-the-skills-1",
    category: "Data Science",
    img: "/course-1.jpg",
    lesson: 43,
    point: 5,
    teacherName: "Jim Séchen",
    teacherİmage: "/teacher-1.jpg",
    price: 0,
  },
  {
    id: 2,
    title: "Fundamentals of music theory Learn new",
    slug:"fundamentals-of-music-theory-learn-new-2",
    category: "Data Science",
    img: "/course-2.jpg",
    lesson: 35,
    point: 4,
    teacherName: "Barry Tone",
    teacherİmage: "/teacher-2.jpg",
    price: 32,
  },
  {
    id: 3,
    title: "Bases Matemáticas dios Álgebra Ecuacion",
    slug:"bases-matematicas-dios-algebra-education-3",
    category: "Data Science",
    img: "/course-3.jpg",
    lesson: 22,
    point: 4,
    teacherName: "Samuel Serif",
    teacherİmage: "/teacher-3.jpg",
    price: 22,
  },
  {
    id: 4,
    title: "Strategy law and organization Foundation",
    slug:"strategy-law-and-organization-foundation-4",
    img: "/course-4.jpg",
    category: "Business",
    lesson: 22,
    point: 4.7,
    teacherName: "Elon Gated",
    teacherİmage: "/teacher-4.jpg",
    price: 50,
  },
  {
    id: 5,
    title: "The business Intelligence analyst Course 2023",
    slug:"the-business-intelligence-analyst-course-5",
    category: "Art & Design",
    img: "/course-5.jpg",
    lesson: 22,
    point: 4.2,
    teacherName: "Eleanor Fant",
    teacherİmage: "/teacher-5.jpg",
    price: 62,
  },
  {
    id: 6,
    title: "Bases Matemáticas dios Álgebra Ecuacion",
    slug:"bases-matematicas-dios-algebra-education-6",
    category: "Art & Design",
    img: "/course-6.jpg",
    lesson: 25,
    point: 4,
    teacherName: "Brian Cumin",
    teacherİmage: "/teacher-6.jpg",
    price: 38,
  },
];

export default coursesData;
