"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { IntlProvider } from "react-intl";
import { PrimeReactProvider } from "primereact/api";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Educal",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <ToastContainer />
      <body className={inter.className}>
        <PrimeReactProvider>
          <IntlProvider locale="tr">
              {pathname !== "/adminPanel" && <Header />}
              {children}
              {pathname !== "/adminPanel" && <Footer />}
          </IntlProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
